services:
  db:
    image: postgres:18
    container_name: postgresql-db-1
    environment:
      POSTGRES_DB: security_test
      POSTGRES_USER: spring_user
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5432:5432"      # Mapeia a porta 5432 para o host, permitindo conex√£o via localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume persistente
    networks:
      - jwt-demo-network

  app:
    image: maven:3.9-eclipse-temurin-21
    container_name: spring_app
    depends_on:
      - db
    ports:
      - "8080:8080"  # Porta do Spring Boot
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    networks:
      - jwt-demo-network

volumes:
  postgres_data:  # Volume para persistir dados do PostgreSQL

networks:
  jwt-demo-network:
    driver: bridge
