services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: security_test
      POSTGRES_USER: spring_user
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - teste-tecnico-api-spring

  app:
    image: maven:3.9-eclipse-temurin-21
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    networks:
      - teste-tecnico-api-spring

volumes:
  postgres_data:

networks:
  teste-tecnico-api-spring:
    driver: bridge
